#!/bin/bash

# Change directory to /ceremonyclient/
cd /ceremonyclient/

# Kill existing tmux session
tmux kill-session -t node

# Pull the latest changes from the repository
git pull --rebase

# Checkout the release branch
git checkout release

# Create a new tmux session
tmux new-session -d -s node

# Change directory inside the tmux session and run the script
tmux send-keys -t node "cd /ceremonyclient/node && ./release_autorun.sh" C-m
