#!/bin/bash

# Clear machine-id
if [ -f /etc/machine-id ]; then
    sudo cat /dev/null > /etc/machine-id
fi

if [ -f /var/lib/dbus/machine-id ]; then
    sudo rm -f /var/lib/dbus/machine-id
fi

# Linking /var/lib/dbus/machine-id to /etc/machine-id means it will not 
# need to be regenerated later and it will always be the same.
sudo ln -s /etc/machine-id /var/lib/dbus/machine-id
