#!/bin/bash
set -e

# Update the apt package index
sudo apt-get update

# Install packages to allow apt to use a repository over HTTPS
sudo apt-get install -y ca-certificates curl gnupg mc

# Add Docker's official GPG key
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Set up the Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the apt package index (again)
sudo apt-get update

# Install Docker Engine, containerd, and Docker Compose
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Create docker group if it doesn't exist
if ! getent group docker >/dev/null; then
    sudo groupadd docker
fi

# Add user to the docker group
if ! groups $USER | grep &>/dev/null "\bdocker\b"; then
    sudo usermod -aG docker $USER
    echo "You need to log out and log back in for the group changes to take effect."
fi

# Print Docker version
docker --version

echo "Docker Engine has been successfully installed on your Ubuntu system!"

# Install Satori
cd ~
wget -P ~/ https://satorinet.io/static/download/linux/satori.zip
unzip ~/satori.zip
rm ~/satori.zip
cd ~/.satori
sudo apt install -y python3-venv
bash install.sh
bash install_service.sh

echo "Satori has been installed. Starting the service..."
journalctl -fu satori.service
