#!/bin/bash

set -e

sudo apt update
sudo apt install -y mc

if ! getent group docker >/dev/null; then
    sudo groupadd docker
fi

if ! groups $USER | grep &>/dev/null "\bdocker\b"; then
    sudo usermod -aG docker $USER
    echo "You need to log out and log back in for the group changes to take effect."
fi

cd ~
wget -P ~/ https://satorinet.io/static/download/linux/satori.zip
unzip ~/satori.zip
rm ~/satori.zip

cd ~/.satori
sudo apt install -y python3-venv
bash install.sh
bash install_service.sh
journalctl -fu satori.service
